export default {
  index: {
    title: '首页',
    theme: {
      layout: 'raw', // 落地页：去掉文档侧栏/目录，完全自定义
      sidebar: false,
      toc: false,
      breadcrumb: false,
      pagination: false,
      footer: false,
      timestamp: false,
    },
  },
  otSection: { type: 'separator', title: 'OT 篇' },
  ot1: 'O1 · 全量广播',
  ot2: 'O2 · 操作化',
  ot3: 'O3 · 版本定序',
  ot4: 'O4 · transform',
  ot5: 'O5 · 客户端状态',
  ot6: 'O6 · 快照与 Undo',
  'ot-practice': '实战 · Mini Docs',
  crdtSection: { type: 'separator', title: 'CRDT 篇' },
  crdt1: 'C1 · 合并与收敛',
  crdt2: 'C2 · 版本向量',
  crdt3: 'C3 · Register',
  crdt4: 'C4 · Set 与删除',
  crdt5: 'C5 · Map 文档',
  crdt6: 'C6 · Sequence 正文',
  'crdt-practice': '实战 · Mini Doc',
};
